"""Generate manuscript-facing tables from frozen C-ESD verification code.

Theory authority: CESD-THEORY-FREEZE-2026-09-04-v1.
No model logic is reimplemented here: this script imports the Stage-4/7
verification modules and serializes their canonical witness outputs.
"""
from __future__ import annotations

import csv
import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VER = ROOT / "verification"
OUT = ROOT / "tables"
OUT.mkdir(exist_ok=True)


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


s4 = load_module("stage04_cesd_minimal", VER / "stage04_cesd_minimal.py")
s7 = load_module("stage07_cesd_welfare_generality", VER / "stage07_cesd_welfare_generality.py")

rows = [
    ("B-T", "SU member minus IS welfare", float(s4.SU_T[0][0] - s4.IS_T[0][0])),
    ("B-X", "SU member minus IS welfare", float(s4.SU_X[0][0] - s4.IS_X[0][0])),
    ("FULL", "SU member minus IS welfare", float(s4.SU_F[0][0] - s4.IS_F[0][0])),
    ("FULL", "SU member CS component", float(s7.dCS)),
    ("FULL", "SU member domestic-profit component", float(s7.dPI)),
    ("FULL", "IS global welfare", float(s7.IS["GW"])),
    ("FULL", "SU global welfare", float(s7.SU["GW"])),
    ("FULL", "SW global welfare", float(s7.SW["GW"])),
    ("FULL", "private SU member distance", float(s7.Dprivate)),
    ("FULL", "constrained-social SU member distance", float(s7.Dsocial)),
    ("FULL", "gamma_W at v=.04, sbar=.25", float(s7.gamma_W)),
]

csv_path = OUT / "generated_results.csv"
with csv_path.open("w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["benchmark", "object", "value"])
    for row in rows:
        w.writerow([row[0], row[1], f"{row[2]:.10f}"])

tex_path = OUT / "generated_results.tex"
with tex_path.open("w", encoding="utf-8") as f:
    f.write("% Generated by scripts/generate_outputs.py; do not hand edit.\n")
    f.write("\\begin{table}[htbp]\n\\centering\n")
    f.write("\\caption{Frozen C-ESD benchmark and welfare outputs}\n")
    f.write("\\label{tab:generated-results}\n")
    f.write("\\begin{tabular}{llr}\n\\toprule\n")
    f.write("Benchmark & Object & Value \\\\\n\\midrule\n")
    for bench, obj, val in rows:
        label = obj.replace("_", "\\_")
        f.write(f"{bench} & {label} & {val:.6f} \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

print(csv_path)
print(tex_path)
