"""Generate manuscript-facing tables from the repaired C-ESD verification chain.

Theory authority: CESD-THEORY-FREEZE-2026-09-04-v2.
No model logic is reimplemented here. This script imports the Stage-7R welfare
refresh, which in turn uses the Stage-4R repaired continuation/policy evaluation,
and serializes the canonical witness outputs.
"""
from __future__ import annotations

import csv
import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VER = ROOT / "verification"
OUT = ROOT / "tables"
OUT.mkdir(exist_ok=True)


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


s7r = load_module("stage07r_cesd_welfare_refresh", VER / "stage07r_cesd_welfare_refresh.py")

rows = [
    ("B-T", "SU member minus IS welfare", float(s7r.dBT)),
    ("B-X", "SU member minus IS welfare", float(s7r.dBX)),
    ("FULL", "SU member minus IS welfare", float(s7r.dFULL)),
    ("FULL", "SU member CS component", float(s7r.dCS)),
    ("FULL", "SU member domestic-profit component", float(s7r.dPI)),
    ("FULL", "IS global welfare net of A", float(s7r.IS["GW"])),
    ("FULL", "SU global welfare net of A", float(s7r.SU["GW"])),
    ("FULL", "SW global welfare net of A", float(s7r.SW["GW"])),
    ("FULL", "private SU member distance", float(s7r.Dprivate)),
    ("FULL", "constrained-social SU member distance", float(s7r.Dsocial)),
    ("FULL", "gamma_W at v=.04, sbar=.25", float(s7r.gamma_W)),
]

csv_path = OUT / "generated_results.csv"
with csv_path.open("w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["benchmark", "object", "value"])
    for row in rows:
        w.writerow([row[0], row[1], f"{row[2]:.10f}"])

row_end = chr(92) * 2 + "\n"
tex_path = OUT / "generated_results.tex"
with tex_path.open("w", encoding="utf-8") as f:
    f.write("% Generated by scripts/generate_outputs.py under CESD-THEORY-FREEZE-2026-09-04-v2; do not hand edit.\n")
    f.write("\\begin{table}[htbp]\n")
    f.write("\\centering\n")
    f.write("\\caption{Repaired v2 C-ESD benchmark and welfare outputs}\n")
    f.write("\\label{tab:generated-results}\n")
    f.write("\\begin{tabular}{llr}\n")
    f.write("\\toprule\n")
    f.write("Benchmark & Object & Value " + row_end)
    f.write("\\midrule\n")
    for bench, obj, val in rows:
        label = obj.replace("_", "\\_")
        f.write(f"{bench} & {label} & {val:.6f} " + row_end)
    f.write("\\bottomrule\n")
    f.write("\\end{tabular}\n")
    f.write("\\end{table}\n")

print(csv_path)
print(tex_path)
